### ISSUE TITLE
DAG capture fails to start if memory is clear before clearing

### ISSUE THREAD

**Issue by dancollins** [wanduow/libtrace#12]
In format_dag25.c:617 we clear any ERF records before the trace started. After this process we have a top pointer and a bottom pointer pointing in the DAG memory map.

Shane made changes so that any packets received during this process are kept so we can read them (meaning the trace starts as soon as we ask it to start). However, there is an error when the memory is already clear. The value to 'top' depends on there being memory to clear.

```c
starttop = dag_advance_stream(FORMAT_DATA->device->fd,
                                        FORMAT_DATA->dagstream,
                                        &bottom);

/* Should probably flush the memory hole now */
while (starttop - bottom > 0) {
	bottom += (starttop - bottom);
	top = dag_advance_stream(FORMAT_DATA->device->fd,
				FORMAT_DATA->dagstream,
				&bottom);
}
FORMAT_DATA->top = top;
FORMAT_DATA->bottom = bottom;
```

If we set the top value before the loop, this issue will be fixed

```c
starttop = dag_advance_stream(FORMAT_DATA->device->fd,
                                        FORMAT_DATA->dagstream,
                                        &bottom);

/* Should probably flush the memory hole now */
top = starttop;
while (starttop - bottom > 0) {
	bottom += (starttop - bottom);
	top = dag_advance_stream(FORMAT_DATA->device->fd,
				FORMAT_DATA->dagstream,
				&bottom);
}
FORMAT_DATA->top = top;
FORMAT_DATA->bottom = bottom;
```

**Comment by salcock** [comment]
I've applied this fix to the develop branch -- thanks for spotting that bug and providing a fix :)
