### ISSUE TITLE
Memory leak in format_dag25.c

### ISSUE THREAD

**Issue by dancollins** [wanduow/libtrace#13]
Staring line lib/format_dat25.c:449 we have the 'dag_init_input' method which will process the input URI and open the DAG device for capture. It makes use of strdup to copy the device name from the URI (presumably to get null termination on the end without destroying the rest of the URI).

In the case the device is already open or the device fails to open this memory will be freed. However in the typical case where a device gets opened, the memory will leak.

We can fix this by adding a free at the end of the method as we don't actually need the device name after we have initialised. This isn't strictly true (as I need to configure the card in dag_config_input, which requires reference to the card name), but it's easy enough to parse it from the URI if we ever need to.

**Comment by salcock** [comment]
Commit 344062798e0c79423dcb5c805191b852b9b48464 in the develop branch should fix this by storing the device name inside the format data. This will allow you to access the name during configuration without having to re-parse the URI. Whenever the format data is freed, we now also free the device name string.
