### ISSUE TITLE
opened pcap is never closed

### ISSUE THREAD

**Issue by TomasKonir** [wanduow/libtrace#18]
Pcap files opened with trace_create() are not closed after trace_destroy(), which causes exhausting number of opened filedescriptors while trying to process more files in sequence.

**Comment by salcock** [comment]
Thanks for reporting this.

Should be fixed in commit 2e915908dc5b2a1b880974dbcd3b0cdf857fb23c and the final libtrace 4 release will include this fix.

In the meantime, I'd recommend using pcapfile: rather than pcap: to read pcap files to avoid this problem.

**Comment by TomasKonir** [comment]
I tried to use pcapfile instead of pcap, but there is the same leaking. After trace_destroy() the pcap files are still opened (in /proc/$PID/fd/*). I'm using libtrace 3.0.21.
