### ISSUE TITLE
visual studio build

### ISSUE THREAD

**Issue by moffel** [wanduow/libtrace#20]
The provided solution for visual studio is not up to date. 

- there are c and h files missing
- invalid (non ASCII) characters in c files
- absolute path to other projects like "C:\Users\root\Documents\Visual Studio 2005\Projects\WpdPack\Include"

I'm using Visual Studio 2015 Update 1 and moved config-win.h to lib/config.h as stated in WIN32.txt.

**Comment by salcock** [comment]
Hello,

We have not supported Windows for a very long time now. The solution you are referring to has not been touched in 8 years and I suspect it will not be a simple task to update it to work with the last 8 years of libtrace development.

From our perspective, the best way forward would be to remove the old visual studio solutions and to be more explicit in our documentation that we do not support Windows any more.

If anyone out there wants to make libtrace work with Windows again, we would welcome such an effort and are happy to provide whatever support might be required to make that happen.
