### ISSUE TITLE
Support DPDK 2.2

### ISSUE THREAD

**Issue by rosenbaumalex** [wanduow/libtrace#21]
when is the porting to DPDK-2.2 planned?
is anyone already working on this?

we're trying to get this working, so once we have something we'll be glad to contribute back.

Alex

**Comment by rsanger** [comment]
We have no plan at the the moment and no one is currently working on this.
However this is certainly something we want to support, just a matter of finding the time.

It is great to see people interested in this, we will accept pull requests and are happy to provide assistance if you have any questions about the code.
Any feedback you have on the parallel API is also welcomed.

Thanks,
Richard

**Comment by EaseTheWorld** [comment]
Anybody still working on this?
I look forward to using DPDK 2.2 with libtrace.

**Comment by rsanger** [comment]
I've updated [develop](https://github.com/wanduow/libtrace/tree/develop/) to support the newest versions of DPDK including 2.2.

**Comment by EaseTheWorld** [comment]
Thank you for update.
and FYI, CONFIG_RTE_BUILD_COMBINE_LIBS is deprecated since dpdk 16.04.
It is always 'y', because libdpdk.a is a link-script(no build cost).
