### ISSUE TITLE
__attribute__((pure)) optimized out some getter functions.

### ISSUE THREAD

**Issue by EaseTheWorld** [wanduow/libtrace#23]
I found libtrace very useful. Thank you guys.

Some getter functions accepts buffer and return the same.
So I just ignored the return value... then the logic didn't work.
For example,
  ```
  trace_get_source_address_string(packet, buf, len) // A
  printf("A buf=%s\n", buf);  // doesn't work.
  char* p = trace_get_source_address_string(packet, buf, len) // B
  printf("B buf=%s\n", buf);  // works fine.
```

This is because  trace_get_source_address_string is declared with the compiler optimization __attribute__((pure)), which optimizes out the function if it doesn't use any global variables.
Compiler removes the first line because I didn't use return value.
(I used gcc 4.4.7 20120313 with no option.)

**Comment by salcock** [comment]
You really shouldn't be ignoring the return value of these functions, though. To quote the documentation of trace_get_source_address_string from libtrace.h:

`Returns NULL if no valid address is available.`

If this happens, your case A will print random gibberish. Case B at least gives the programmer to check that the contents of buf are valid before printing them. 

The compiler optimisation is there to encourage people to not ignore the return value, as they should get a compiler warning if they do.

**Comment by EaseTheWorld** [comment]
Oh you are right.
I will check the return value.
Thank you.
2016. 3. 17. 오전 5:52에 "Shane Alcock" <notifications@github.com>님이 작성:
