### ISSUE TITLE
Libtrace 4.0 tracesplit no compression

### ISSUE THREAD

**Issue by Carisbrooke** [wanduow/libtrace#24]
Hello,

Using the latest git libtrace 4.0 and running the following:

tracesplit -Z gzip -i 600 dpdk:0000:03:00.0 pcapfile:10min_trace.pcap.gz

(no output or errors after the command line)

The output file is not comrpessed:

file 10min_trace.pcap.gz-1458152907.gz
10min_trace.pcap.gz-1458152907.gz: tcpdump capture file (little-endian) - version 2.4 (Ethernet, capture length 65536)

Any ideas ?

**Comment by salcock** [comment]
Try using the -z option to set a compression level > 0. The default compression level is zero, which will result in an uncompressed output file.

**Comment by Carisbrooke** [comment]
Thank you that was the problem, also noticed the file always ends .gz whatever the compression used.
