### ISSUE TITLE
magic field in libtrace_stat_t, necessary?

### ISSUE THREAD

**Issue by EaseTheWorld** [wanduow/libtrace#34]
I want to calc some stats and found clearing stat api is missing. memset can't help because of magic field. I think the field is kind of insurance to protect from corruption, but that requires to create heap even if all I need is local var in stack.

**Comment by EaseTheWorld** [comment]
If you still think magic field is necessary, i could add clear api of course.

**Comment by rsanger** [comment]
The magic exists primarily to ensure this is allocated via the API, nothing to do with corruption. The thinking behind this being that in the future we could add another statistic to the end of the structure without breaking old code. This is perhaps a little bit over-engineered, but hopefully not to complicated for a user.

Missing clear is an oversight and is probably best added to the API.

P.S. We do clear the flags when [trace_get_statistics()](https://github.com/wanduow/libtrace/blob/c46b7eab33333edcc7ae4b575dda0f0c2a123755/lib/trace.c#L2154-L2158) is called so you don't need to clear this if you are simply calling that again.

**Comment by EaseTheWorld** [comment]
I make PR #35.

**Comment by rsanger** [comment]
Thanks for the PR

Supporting stack this way is a nice compromise
