### ISSUE TITLE
Header files should be installed in a sub-directory

### ISSUE THREAD

**Issue by jer-gentoo** [wanduow/libtrace#44]
/usr/include is not a safe path to store files.

Cf. https://bugs.gentoo.org/show_bug.cgi?id=604660

**Comment by salcock** [comment]
cff18196808f8369d7825aa1d60de86236bce0df should resolve the worst filename conflicts, without too much impact on existing users.

**Comment by salcock** [comment]
If there are no further complaints, I'll close this issue for now
